export const TRADINGVIEW_MAJOR_SYMBOLS = {
  BTC: "BINANCE:BTCUSDT",
  ETH: "BINANCE:ETHUSDT",
  SOL: "BINANCE:SOLUSDT",
  BNB: "BINANCE:BNBUSDT",
  XRP: "BINANCE:XRPUSDT",
  ADA: "BINANCE:ADAUSDT",
  DOGE: "BINANCE:DOGEUSDT",
  AVAX: "BINANCE:AVAXUSDT",
  DOT: "BINANCE:DOTUSDT",
  LINK: "BINANCE:LINKUSDT",
  MATIC: "BINANCE:MATICUSDT",
  POL: "BINANCE:POLUSDT",
  LTC: "BINANCE:LTCUSDT",
  TRX: "BINANCE:TRXUSDT",
  TON: "BINANCE:TONUSDT",
  BCH: "BINANCE:BCHUSDT",
  UNI: "BINANCE:UNIUSDT",
  ATOM: "BINANCE:ATOMUSDT",
  NEAR: "BINANCE:NEARUSDT",
  APT: "BINANCE:APTUSDT",
  ARB: "BINANCE:ARBUSDT",
  OP: "BINANCE:OPUSDT",
  PEPE: "BINANCE:PEPEUSDT",
};

export const STABLECOIN_SYMBOLS = {
  USDT: { coingeckoId: "tether", title: "Tether stability" },
  USDC: { coingeckoId: "usd-coin", title: "USD Coin stability" },
  DAI: { coingeckoId: "dai", title: "Dai stability" },
};

export const COINGECKO_IDS_BY_SYMBOL = {
  BTC: "bitcoin",
  ETH: "ethereum",
  SOL: "solana",
  BNB: "binancecoin",
  XRP: "ripple",
  ADA: "cardano",
  DOGE: "dogecoin",
  AVAX: "avalanche-2",
  DOT: "polkadot",
  LINK: "chainlink",
  MATIC: "matic-network",
  POL: "polygon-ecosystem-token",
  LTC: "litecoin",
  TRX: "tron",
  TON: "the-open-network",
  BCH: "bitcoin-cash",
  UNI: "uniswap",
  ATOM: "cosmos",
  NEAR: "near",
  APT: "aptos",
  ARB: "arbitrum",
  OP: "optimism",
  PEPE: "pepe",
  USDT: "tether",
  USDC: "usd-coin",
  DAI: "dai",
};

export const GECKOTERMINAL_NETWORK_ALIASES = {
  ethereum: "eth",
  eth: "eth",
  "erc20": "eth",
  "erc-20": "eth",
  bitcoin: "bitcoin",
  bsc: "bsc",
  "bnb smart chain": "bsc",
  polygon: "polygon_pos",
  "polygon pos": "polygon_pos",
  arbitrum: "arbitrum",
  optimism: "optimism",
  base: "base",
  avalanche: "avax",
  avax: "avax",
  solana: "solana",
  tron: "tron",
  "tron trc20": "tron",
};

export function cleanCryptoSymbol(symbol = "") {
  return String(symbol).trim().toUpperCase();
}
