export const cryptoAssets = [
  { symbol: "BTC", name: "Bitcoin", network: "Bitcoin", color: "#F7931A", price: 103842.18, coingeckoId: "bitcoin" },
  { symbol: "ETH", name: "Ethereum", network: "Ethereum", color: "#627EEA", price: 3826.41, coingeckoId: "ethereum" },
  { symbol: "USDT", name: "Tether", network: "TRC20", color: "#26A17B", price: 1, coingeckoId: "tether" },
  { symbol: "USDC", name: "USD Coin", network: "ERC20", color: "#2775CA", price: 1, coingeckoId: "usd-coin" },
  { symbol: "BNB", name: "BNB", network: "BNB Smart Chain", color: "#F3BA2F", price: 612.76, coingeckoId: "binancecoin" },
  { symbol: "SOL", name: "Solana", network: "Solana", color: "#14F195", price: 178.3, coingeckoId: "solana" },
  { symbol: "XRP", name: "XRP", network: "XRP Ledger", color: "#8EA1B2", price: 0.61, coingeckoId: "ripple" },
  { symbol: "ADA", name: "Cardano", network: "Cardano", color: "#0033AD", price: 0.72, coingeckoId: "cardano" },
  { symbol: "DOGE", name: "Dogecoin", network: "Dogecoin", color: "#C2A633", price: 0.16, coingeckoId: "dogecoin" },
  { symbol: "AVAX", name: "Avalanche", network: "Avalanche C-Chain", color: "#E84142", price: 36.82, coingeckoId: "avalanche-2" },
  { symbol: "DOT", name: "Polkadot", network: "Polkadot", color: "#E6007A", price: 7.12, coingeckoId: "polkadot" },
  { symbol: "LINK", name: "Chainlink", network: "Ethereum ERC-20", color: "#375BD2", price: 18.44, coingeckoId: "chainlink" },
  { symbol: "LTC", name: "Litecoin", network: "Litecoin", color: "#A6A9AA", price: 86.21, coingeckoId: "litecoin" },
  { symbol: "TRX", name: "TRON", network: "TRON TRC20", color: "#EF0027", price: 0.11, coingeckoId: "tron" },
  { symbol: "POL", name: "Polygon", network: "Polygon PoS", color: "#8247E5", price: 0.69, coingeckoId: "polygon-ecosystem-token" },
  { symbol: "BCH", name: "Bitcoin Cash", network: "Bitcoin Cash", color: "#0AC18E", price: 452.9, coingeckoId: "bitcoin-cash" },
  { symbol: "UNI", name: "Uniswap", network: "Ethereum ERC-20", color: "#FF007A", price: 10.14, coingeckoId: "uniswap" },
  { symbol: "ATOM", name: "Cosmos", network: "Cosmos Hub", color: "#2E3148", price: 8.73, coingeckoId: "cosmos" },
  { symbol: "NEAR", name: "NEAR Protocol", network: "NEAR", color: "#00EC97", price: 6.18, coingeckoId: "near" },
  { symbol: "ARB", name: "Arbitrum", network: "Arbitrum One", color: "#28A0F0", price: 1.16, coingeckoId: "arbitrum" },
].map((asset) => ({
  ...asset,
  type: "crypto",
  chartSymbol: `BINANCE:${asset.symbol}USDT`,
}));
